# pilot
stages:
- name: group_corridor_on
  map: hospital_1_bare
  robot: jackal
  tm_robots: scenario
  tm_obstacles: scenario
  episodes: 1
  seed: 74000
  timeout: 90s
  config:
    scenario:
      file: group_corridor
      gesture_mode: enabled
