# pilot
stages:
- name: group_open_off
  map: hospital_1_bare
  robot: jackal
  tm_robots: scenario
  tm_obstacles: scenario
  episodes: 1
  seed: 74200
  timeout: 90s
  config:
    scenario:
      file: group_open
      gesture_mode: disabled
