# pilot
stages:
- name: hhi_corridor_off
  map: hospital_1_bare
  robot: jackal
  tm_robots: scenario
  tm_obstacles: scenario
  episodes: 1
  seed: 75000
  timeout: 90s
  config:
    scenario:
      file: hhi_corridor
      gesture_mode: disabled
      contact_mode: enabled
