name: landmarks
launch:
  sim: gazebo
  headless: true
  env.n: 1
stages:
- name: h_pharmacy
  map: hospital_1
  robot: jackal[camera=vln_navid]
  episodes: 1
  timeout: 240.0
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: landmark_pharmacy
- name: h_laboratory
  map: hospital_1
  robot: jackal[camera=vln_navid]
  episodes: 1
  timeout: 240.0
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: landmark_laboratory
- name: h_operating_room
  map: hospital_1
  robot: jackal[camera=vln_navid]
  episodes: 1
  timeout: 240.0
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: landmark_operating_room
- name: h_waiting_area
  map: hospital_1
  robot: jackal[camera=vln_navid]
  episodes: 1
  timeout: 360.0
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: landmark_waiting_area
- name: h_reception_then_ward
  map: hospital_1
  robot: jackal[camera=vln_navid]
  episodes: 1
  timeout: 420.0
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: landmark_reception_then_ward
